mongodb:
  uri: "mongodb://admin:admin@mongodb:32717/dev"

serviceMonitor:
  additionalLabels:
    release: prometheus-grafana-stack

service:
  labels: {}
  annotations: {}
  port: 9216
  # type: ClusterIP
  type: NodePort
  nodePort: 32106
  portName: metrics
