kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: test-pvc-retain
spec:
    storageClassName: trungle-nfs-retain
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 10Mi
