[all]
master    ansible_host=192.168.61.134      ip=192.168.61.134
worker    ansible_host=192.168.61.129      ip=192.168.61.129
worker2   ansible_host=192.168.61.135      ip=192.168.61.135

[kube-master]
master

[kube-node]
worker
worker2

[etcd]
master

[k8s-cluster:children]
kube-node
kube-master

[calico-rr]

[vault]
master
worker
worker2