version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
    ports:
      - "5432:5432"
    volumes:
      - postgres/data:/data/postgres
      - postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # Automatically execute SQL file after creating instance

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8080:8088"
    environment:
      - SUPERSET_SECRET_KEY=trungle
    command: ["bash", "-c", "superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && superset db upgrade && superset init && /usr/bin/run-server.sh"]

  localstack-pro:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_pro_main}"
    image: localstack/localstack-pro  # Required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # Required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
